version: '3'
services:
  nginx:
    image: nginx:1.17.2
    container_name: nginx
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - hplus
    volumes:
      - ./webapp/load_balance_nginx.conf:/etc/nginx/conf.d/hplus.conf
  hplus:
    image: michaelbjames/hoogleplus_web:latest
    networks:
      - hplus
    volumes:
      - ./logs/:/var/log/hplus/


networks:
  hplus:
