name: HooglePlus
version: 0.1.0.0
github: "TyGus/hoogle_plus"
license: BSD3
author: "Zheng Guo"
maintainer: "zhg069@eng.ucsd.edu"

extra-source-files:
  - README.md
data-files:
  - InternalTypeGen.hs

description: Please see the README

dependencies:
  - aeson
  - ansi-wl-pprint
  - base
  - bytestring
  - Cabal
  - cereal
  - ChasingBottoms
  - cmdargs
  - conduit
  - conduit-extra
  - containers
  - deepseq
  - directory
  - extra
  - filepath
  - ghc
  - ghc-paths
  - hashable
  - haskell-src-exts
  - hint
  - hoogle
  - http-conduit
  - http-types
  - indents
  - leancheck
  - lens
  - logict
  - MissingH
  - mtl
  - parsec
  - pretty-simple
  - process
  - QuickCheck
  - regex-compat
  - regex-posix
  - resourcet
  - safe
  - smallcheck
  - sort
  - split
  - text
  - time
  - transformers
  - unordered-containers
  - uuid
  - z3
  - ghci
  - ghc-boot-th
  - silently
  - yaml
  - QuickCheck
  - random
  - souffle-haskell

library:
  source-dirs:
    - src
  verbatim:
    - "includes: z3.h"
  extra-libraries:
    - z3
  ghc-options:
    - -O2
    - -Wall
  cxx-options:
    - -std=c++17
  when:
    - condition: os(linux)
      extra-libraries: stdc++
    - condition: os(darwin)
      extra-libraries: c++

executables:
  hplus:
    main: HooglePlus.hs
    source-dirs: app
    ghc-options:
      # - -fext-core
      - -Wall
      - -rtsopts
      # - -ddump-simpl 
      # - -dsuppress-idinfo
      # - -dsuppress-coercions 
      # - -dsuppress-type-applications
      # - -dsuppress-uniques 
      # - -dsuppress-module-prefixes
      # - -prof
      # - -fprof-auto
      - -O2
    dependencies:
      - HooglePlus

tests:
  spec:
    main: Test.hs
    source-dirs: test
    ghc-options:
      - -O2
    dependencies:
      - HooglePlus
      - tasty
      - tasty-hunit
