name: HooglePlus
version: 0.1.0.0
github: "davidmrdavid/hoogle_plus"
license: BSD3
author: "Zheng Guo"
maintainer: "zhg069@ucsd.edu"

extra-source-files:
- README.md
data-files:
- InternalTypeGen.hs

description: Please see the README

dependencies:
- aeson
- ansi-terminal
- ansi-wl-pprint
- array
- async
- base
- bimap
- bytestring
- Cabal
- cereal
- ChasingBottoms
- cmdargs
- conduit
- conduit-extra
- containers
- directory
- extra
- filepath
- ghc
- ghc-paths
- hashable
- haskell-src-exts
- heap
- hint
- html
- http-conduit
- http-types
- indents
- lens
- logict
- MissingH
- mtl
- packdeps
- parsec
- pqueue
- pretty-simple
- pretty-tree
- process
- regex-compat
- regex-posix
- resourcet
- safe
- smallcheck
- sort
- split
- stm
- text
- time
- transformers
- transformers-compat
- unordered-containers
- uuid
- vector
- z3

library:
  source-dirs:
  - src
  other-extensions:
  - TemplateHaskell
  - Rank2Types
  - FlexibleInstances
  - TypeSynonymInstances
  - FlexibleContexts
  verbatim:
  - "includes: z3.h"
  extra-libraries: z3

executables:
  hplus:
    main: HooglePlus.hs
    source-dirs: app
    ghc-options:
    - -rtsopts
    - -O2
    dependencies:
    - HooglePlus
  webapp:
    main: Main.hs
    source-dirs:
    - webapp/app
    - webapp/src
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HooglePlus
    - yesod-core
    - yesod-form
    - yesod-static
    - shakespeare

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - HooglePlus
      - hspec
      - hspec-discover
    build-tools: hspec-discover
