name: HooglePlus
version: 0.2.0.0
github: "TyGus/hoogle_plus"
license: "MIT"
author: "Zheng Guo"
maintainer: "zhg069@eng.ucsd.edu"

extra-source-files:
- README.md
data-files:
- InternalTypeGen.hs

description: Please see the README

dependencies:
- aeson
- async
- ansi-wl-pprint
- array
- base
- table-layout
- brittany
- bytestring
- cereal
- ChasingBottoms
- cmdargs
- containers
- deepseq
- directory
- extra
- exceptions
- ghc
- ghc-boot-th
- ghc-paths
- ghci
- hashable
- hashtables
- haskell-src-exts
- hint
- hoogle
- leancheck
- lens
- logict
- MissingH
- mtl
- network
- parsec
- pretty-simple
- process
- QuickCheck
- random
- regex-compat
- silently
- smallcheck
- sort
- split
- stm
- text
- time
- transformers
- unordered-containers
- uuid
- yaml
- z3
- compact-coupled-terms

default-extensions:
- BangPatterns
- ConstraintKinds
- DeriveDataTypeable
- DeriveFunctor
- DeriveGeneric
- FlexibleContexts
- FlexibleInstances
- LambdaCase
- MultiParamTypeClasses
- OverloadedStrings
- Rank2Types
- ScopedTypeVariables
- TemplateHaskell
- TupleSections
- TypeSynonymInstances
- UndecidableInstances
- ViewPatterns
- PatternSynonyms
- GADTs
- StandaloneDeriving
- MagicHash
- GeneralizedNewtypeDeriving

library:
  source-dirs:
  - src
  verbatim:
  - "includes: z3.h"
  extra-libraries: z3

executables:
  hplus:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -rtsopts
    - -O2
    - -Wall
    dependencies:
    - HooglePlus

  interpreter:
    main: Interpreter.hs
    source-dirs: app
    ghc-options:
    - -rtsopts
    - -O2
    - -Wall
    - -main-is Interpreter
    dependencies:
    - HooglePlus

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - HooglePlus
      - hspec
      - hspec-discover
    build-tools: hspec-discover
