packages:
- .
resolver: lts-17.1
extra-deps:
  - table-layout-0.8.0.3
  - data-default-instances-base-0.1.0.1
  - pretty-tree-0.1.0.0
  - z3-408.0

compiler: ghc-8.10.1
setup-info:
  ghc:
    linux64-custom-yields:
      8.10.1:
        url: "https://github.com/mistzzt/build-ghc-no-omit-yields/releases/download/v8.10.1/ghc-8.10.1-x86_64-unknown-linux.tar.xz"
    macosx-custom-yields:
      8.10.1:
        url: "https://github.com/mistzzt/build-ghc-no-omit-yields/releases/download/v8.10.1/ghc-8.10.1-x86_64-apple-darwin.tar.xz"
ghc-variant: yields
