packages:
- .
resolver: lts-18.28
extra-deps:
  - table-layout-0.9.1.0
  - data-default-instances-base-0.1.0.1
  - z3-408.1
  - leancheck-0.9.3
  - hoogle-5.0.18.2
  - MissingH-1.5.0.1
  - data-tree-print-0.1.0.2
  - brittany-0.13.1.2
  - language-dot-0.1.1
  - ./compact-coupled-terms
  - git: https://github.com/jkoppel/equivalence.git
    commit: e58c9c0b369f9b8105744cc0342f2e69929b11bf

compiler: ghc-8.10.7
setup-info:
  ghc:
    linux64-custom-yields:
      8.10.7:
        url: "https://github.com/TyGuS/hoogle_plus/releases/download/hectare-0.1/ghc-8.10.7-x86_64-unknown-linux.tar.xz"
ghc-variant: yields