export const ADD_CANDIDATE = "ADD_CANDIDATE";
export const UPDATE_CANDIDATE_USAGE = "UPDATE_CANDIDATE_USAGE";
export const FETCH_MORE_CANDIDATE_USAGES = "FETCH_MORE_CANDIDATE_USAGES";
export const SET_SEARCH_STATUS = "SET_SEARCH_STATUS";

export const ADD_FACT = "ADD_FACT";
export const SET_EXAMPLES = "SET_EXAMPLES";
export const SET_EXAMPLE_EDITING_ROW = "SET_EDITING_CELLS";
export const SET_SEARCH_TYPE = "SET_SEARCH_TYPE";
export const SET_NEW_SEARCH = "SET_NEW_SEARCH";
export const SET_COMPONENTS = "SET_COMPONENTS";

export const INCREASE_ARGS = "INCREASE_ARGS";
export const DECREASE_ARGS = "DECREASE_ARGS";
export const SET_ARG_NUM = "SET_ARG_NUM";

export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_CLOSE = "MODAL_CLOSE";
export const SET_TYPE_OPTIONS = "SET_TYPE_OPTIONS";