export const ADD_CANDIDATE = "ADD_CANDIDATE";
export const UPDATE_CANDIDATE_USAGE = "UPDATE_CANDIDATE_USAGE";
export const ADD_FACT = "ADD_FACT";
export const SET_FACTS = "SET_FACTS";
export const SET_EDITING_CELLS = "SET_EDITING_CELLS";

export const SET_SEARCH_TYPE = "SET_SEARCH_TYPE";
export const SET_NEW_SEARCH = "SET_NEW_SEARCH";

export const INCREASE_ARGS = "INCREASE_ARGS";
export const DECREASE_ARGS = "DECREASE_ARGS";
export const SET_ARG_NUM = "SET_ARG_NUM";
