name:    app2
version: "0.0.0"

dependencies:
- base
- yesod-core
- yesod-form
- shakespeare

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: 
  - src
  - ../src
  other-extensions:
  - TemplateHaskell
  - Rank2Types
  - FlexibleInstances
  - TypeSynonymInstances
  - FlexibleContexts
  verbatim:
  - "includes: z3.h"
  extra-libraries: z3
  dependencies:
  - base
  - Cabal
  - MissingH
  - aeson
  - ansi-terminal
  - ansi-wl-pprint
  - bimap
  - bytestring
  - cereal
  - cmdargs
  - conduit
  - conduit-extra
  - containers
  - directory
  - extra
  - filepath
  - hashable
  - haskell-src-exts
  - heap
  - hint
  - html
  - http-conduit
  - http-types
  - indents
  - lens
  - logict
  - mtl
  - packdeps
  - parsec
  - pqueue
  - pretty-simple
  - process
  - regex-compat
  - resourcet
  - safe
  - sort
  - split
  - split
  - text
  - time
  - transformers
  - transformers-compat
  - unordered-containers
  - vector

# Runnable executable for our application
executables:
  app2:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - app2
